export const economyGraph = {
  rootId: 'economy',
  nodes: [
    { id: 'economy', label: 'THE ECONOMY', category: 'system', summary: 'A connected system of agents, institutions, markets and outcomes.' },
    { id: 'households', label: 'Households', category: 'agent', summary: 'Supply labour, consume, save and borrow.', expands: ['node:households'] },
    { id: 'firms', label: 'Firms', category: 'agent', summary: 'Employ workers, produce output and invest.' },
    { id: 'government', label: 'Government', category: 'institution', summary: 'Taxes, spends, regulates and issues public debt.' },
    { id: 'banks', label: 'Commercial banks', category: 'institution', summary: 'Take deposits, extend credit and make payments.' },
    { id: 'central-bank', label: 'Central bank', category: 'institution', summary: 'Sets monetary policy and supports payment and financial stability.' },
    { id: 'labour-market', label: 'Labour market', category: 'market', summary: 'Matches workers with employers and sets wages and employment.' },
    { id: 'housing-market', label: 'Housing market', category: 'market', summary: 'Connects housing supply, prices, rents and mortgage finance.' },
    { id: 'interest-rates', label: 'Interest rates', category: 'variable', summary: 'Shape the price of credit, saving and asset valuation.', expands: ['node:rates'] },
    { id: 'demand', label: 'Aggregate demand', category: 'outcome', summary: 'Total spending on domestic goods and services.' },
    { id: 'inflation', label: 'Inflation', category: 'outcome', summary: 'The rate at which the general price level changes.' },

    { id: 'labour-income', label: 'Labour income', category: 'variable', revealedBy: 'node:households' },
    { id: 'disposable-income', label: 'Disposable income', category: 'variable', revealedBy: 'node:households' },
    { id: 'consumption', label: 'Consumption', category: 'variable', revealedBy: 'node:households' },
    { id: 'firm-revenue', label: 'Firm revenue', category: 'variable', revealedBy: 'node:households' },
    { id: 'employment', label: 'Employment', category: 'variable', revealedBy: 'node:households' },
    { id: 'mortgage-credit', label: 'Mortgage credit', category: 'mechanism', revealedBy: 'relationship:household-bank-credit' },
    { id: 'deposits', label: 'Deposits', category: 'mechanism', revealedBy: 'relationship:household-bank-credit' },
    { id: 'interest-payments', label: 'Interest payments', category: 'mechanism', revealedBy: 'relationship:household-bank-credit' },
    { id: 'mortgage-costs', label: 'Mortgage costs', category: 'variable', revealedBy: 'node:rates' },
    { id: 'saving-returns', label: 'Saving returns', category: 'variable', revealedBy: 'node:rates' },
    { id: 'asset-wealth', label: 'Asset prices / wealth', category: 'variable', revealedBy: 'node:rates' },
    { id: 'expectations', label: 'Expectations', category: 'mechanism', revealedBy: 'node:rates' }
  ],
  layout: {
    economy: { x: 600, y: 92 },
    households: { x: 255, y: 235 },
    firms: { x: 600, y: 235 },
    government: { x: 945, y: 235 },
    banks: { x: 330, y: 408 },
    'central-bank': { x: 600, y: 408 },
    'labour-market': { x: 112, y: 408 },
    'housing-market': { x: 890, y: 408 },
    'interest-rates': { x: 600, y: 568 },
    demand: { x: 365, y: 735 },
    inflation: { x: 835, y: 735 },
    'labour-income': { x: 90, y: 590 },
    'disposable-income': { x: 220, y: 735 },
    consumption: { x: 500, y: 735 },
    'firm-revenue': { x: 650, y: 735 },
    employment: { x: 760, y: 590 },
    'mortgage-credit': { x: 190, y: 515 },
    deposits: { x: 190, y: 330 },
    'interest-payments': { x: 425, y: 515 },
    'mortgage-costs': { x: 425, y: 645 },
    'saving-returns': { x: 600, y: 645 },
    'asset-wealth': { x: 775, y: 645 },
    expectations: { x: 955, y: 645 }
  },
  relationships: [
    { id: 'economy-households', source: 'economy', target: 'households', name: 'Household activity', direction: 'two-way', category: 'real economy', description: 'Households supply labour and receive income, then make consumption, saving and borrowing decisions.' },
    { id: 'economy-firms', source: 'economy', target: 'firms', name: 'Production and output', direction: 'two-way', category: 'real economy', description: 'Firms combine labour and capital to produce goods and services that meet demand.' },
    { id: 'economy-government', source: 'economy', target: 'government', name: 'Public sector', direction: 'two-way', category: 'fiscal system', description: 'Government collects taxes, purchases output, transfers income and provides public services.' },
    { id: 'households-labour', source: 'households', target: 'labour-market', name: 'Labour supply', direction: 'two-way', category: 'income channel', description: 'Households supply skills and time; wages and job availability determine labour income.' },
    { id: 'firms-labour', source: 'firms', target: 'labour-market', name: 'Hiring and wages', direction: 'two-way', category: 'income channel', description: 'Firms demand workers. Hiring responds to expected sales, productivity and labour costs.' },
    { id: 'household-bank-credit', source: 'households', target: 'banks', name: 'Household finance', direction: 'two-way', category: 'credit channel', description: 'Households hold bank deposits and borrow through mortgages and other credit. Loan terms affect spending and household balance sheets.', expands: ['relationship:household-bank-credit'] },
    { id: 'firms-bank-credit', source: 'firms', target: 'banks', name: 'Business lending', direction: 'two-way', category: 'credit channel', description: 'Banks provide working-capital and investment finance; firms repay loans with interest.' },
    { id: 'government-banks', source: 'government', target: 'banks', name: 'Public debt and deposits', direction: 'two-way', category: 'financial flows', description: 'Banks hold government securities and provide payment and account services to the public sector.' },
    { id: 'central-bank-rates', source: 'central-bank', target: 'interest-rates', name: 'Policy rate setting', direction: 'forward', category: 'monetary policy', description: 'The central bank changes its policy rate to influence market rates, financial conditions and expectations.' },
    { id: 'rates-households', source: 'interest-rates', target: 'households', name: 'Household interest-rate channels', direction: 'two-way', category: 'monetary transmission', description: 'Rates affect mortgage borrowing costs, saving returns, disposable income, asset wealth and expectations. Through aggregate demand they can also affect employment and labour income.', expands: ['node:rates'] },
    { id: 'banks-housing', source: 'banks', target: 'housing-market', name: 'Mortgage finance', direction: 'two-way', category: 'credit channel', description: 'Mortgage availability and pricing connect credit conditions with housing demand, construction and house prices.' },
    { id: 'rates-housing', source: 'interest-rates', target: 'housing-market', name: 'Housing finance conditions', direction: 'forward', category: 'asset-price channel', description: 'Interest rates affect mortgage affordability, buyer demand, housing valuations and construction.' },
    { id: 'households-demand', source: 'households', target: 'demand', name: 'Consumption spending', direction: 'forward', category: 'spending channel', description: 'Household consumption depends on income, wealth, credit access and expectations.' },
    { id: 'firms-demand', source: 'firms', target: 'demand', name: 'Investment spending', direction: 'forward', category: 'spending channel', description: 'Firms invest when expected returns justify financing and installation costs.' },
    { id: 'government-demand', source: 'government', target: 'demand', name: 'Public spending and taxes', direction: 'two-way', category: 'fiscal channel', description: 'Public purchases add directly to demand; taxes and transfers change private disposable income.' },
    { id: 'demand-inflation', source: 'demand', target: 'inflation', name: 'Demand pressure', direction: 'forward', category: 'price mechanism', description: 'When spending grows faster than productive capacity, firms may raise prices and wages.' },
    { id: 'inflation-policy', source: 'inflation', target: 'central-bank', name: 'Inflation response', direction: 'feedback', category: 'policy feedback', description: 'Inflation outcomes feed into central-bank decisions, creating a feedback loop through policy rates and demand.' },

    { id: 'household-deposits', source: 'households', target: 'deposits', name: 'Saving deposits', direction: 'forward', category: 'balance-sheet channel', description: 'Households hold liquid savings in bank accounts; deposits are a key source of bank funding.', revealedBy: 'relationship:household-bank-credit' },
    { id: 'deposits-banks', source: 'deposits', target: 'banks', name: 'Bank funding', direction: 'forward', category: 'financial flows', description: 'Deposits are liabilities of banks and support payment services and lending.', revealedBy: 'relationship:household-bank-credit' },
    { id: 'banks-mortgage-credit', source: 'banks', target: 'mortgage-credit', name: 'Mortgage origination', direction: 'forward', category: 'credit channel', description: 'Banks assess borrowers and create mortgage credit subject to funding, capital and risk conditions.', revealedBy: 'relationship:household-bank-credit' },
    { id: 'mortgage-households', source: 'mortgage-credit', target: 'households', name: 'Mortgage borrowing', direction: 'forward', category: 'credit channel', description: 'Borrowers receive funds to purchase housing and take on a repayment obligation.', revealedBy: 'relationship:household-bank-credit' },
    { id: 'households-interest-payments', source: 'households', target: 'interest-payments', name: 'Debt service', direction: 'forward', category: 'cash-flow channel', description: 'Borrowers make interest and principal payments, reducing disposable cash flow.', revealedBy: 'relationship:household-bank-credit' },
    { id: 'interest-payments-banks', source: 'interest-payments', target: 'banks', name: 'Loan interest income', direction: 'forward', category: 'financial flows', description: 'Interest payments are income to lenders and part of the price of credit.', revealedBy: 'relationship:household-bank-credit' },

    { id: 'households-labour-income', source: 'households', target: 'labour-income', name: 'Earned income', direction: 'forward', category: 'income channel', description: 'Work generates wages and other labour compensation for households.', revealedBy: 'node:households' },
    { id: 'income-disposable', source: 'labour-income', target: 'disposable-income', name: 'Taxes and transfers', direction: 'forward', category: 'income channel', description: 'Taxes, transfers and other income determine the resources available for spending and saving.', revealedBy: 'node:households' },
    { id: 'disposable-consumption', source: 'disposable-income', target: 'consumption', name: 'Spending decision', direction: 'forward', category: 'spending channel', description: 'Households allocate disposable income between consumption and saving.', revealedBy: 'node:households' },
    { id: 'consumption-firm-revenue', source: 'consumption', target: 'firm-revenue', name: 'Sales revenue', direction: 'forward', category: 'circular flow', description: 'Household spending becomes revenue for firms selling goods and services.', revealedBy: 'node:households' },
    { id: 'revenue-employment', source: 'firm-revenue', target: 'employment', name: 'Output and hiring', direction: 'forward', category: 'circular flow', description: 'Sales prospects affect production plans and firms’ demand for workers.', revealedBy: 'node:households' },
    { id: 'employment-households', source: 'employment', target: 'households', name: 'Jobs and labour income', direction: 'feedback', category: 'feedback loop', description: 'Employment feeds back into household income and future consumption.', revealedBy: 'node:households' },

    { id: 'rates-mortgage-costs', source: 'interest-rates', target: 'mortgage-costs', name: 'Mortgage borrowing costs', direction: 'forward', category: 'cash-flow channel', description: 'Changes in market rates pass into new mortgage rates and, over time, some existing repayments.', revealedBy: 'node:rates' },
    { id: 'rates-saving-returns', source: 'interest-rates', target: 'saving-returns', name: 'Saving returns', direction: 'forward', category: 'income channel', description: 'Higher rates can raise returns on savings, changing household income and incentives to spend now or later.', revealedBy: 'node:rates' },
    { id: 'rates-asset-wealth', source: 'interest-rates', target: 'asset-wealth', name: 'Asset prices and wealth', direction: 'forward', category: 'wealth channel', description: 'Rates influence discount rates, asset valuations, collateral and household wealth.', revealedBy: 'node:rates' },
    { id: 'rates-expectations', source: 'interest-rates', target: 'expectations', name: 'Expectations channel', direction: 'forward', category: 'expectations channel', description: 'Policy signals can change beliefs about future inflation, income and rates, affecting decisions today.', revealedBy: 'node:rates' },
    { id: 'mortgage-costs-households', source: 'mortgage-costs', target: 'households', name: 'Disposable income', direction: 'feedback', category: 'cash-flow channel', description: 'Mortgage costs change cash available for other spending, particularly for indebted households.', revealedBy: 'node:rates' },
    { id: 'wealth-households', source: 'asset-wealth', target: 'households', name: 'Wealth effect', direction: 'feedback', category: 'wealth channel', description: 'Changes in household wealth can influence confidence, collateral and consumption.', revealedBy: 'node:rates' }
  ]
};